#!/usr/bin/env bash

if [[ -z "$1" ]]; then
    echo "USAGE: $0 NUMBER PROB_INPUT [TEMPLATE] [TARGET_NAME]"
    echo "PROB_INPUT - A space separated list of the number of subproblems for each problem"
    exit 1
fi

number="$1"
prob_input="$2"

hw_dir="HW$number"

latex_dir="$(realpath --relative-to="$(pwd)" "$(dirname "${BASH_SOURCE[0]}")")"
template="$latex_dir/template.tex"
target="main.tex"

if [[ -n "$3" ]]; then
    template="$3"
fi

if [[ -n "$4" ]]; then
    target="$4"
fi

mkdir "$hw_dir"
cp "$template" "$hw_dir/$target"
sed -E -i "s|<LATEX_DIR>|../$latex_dir|g" "$hw_dir/$target"
(
    echo ":normal! G"
    echo ":normal! 3k"
    echo ":call MathHomeworkTemplate(\"$prob_input\")"
    echo ":wq"
) > temp

vim -s temp "$hw_dir/$target"
rm temp

